### PR TITLE
remove the fill_value parameter from _pad_simple

### PR DESCRIPTION
**Pull request by hmaarrfk**
Just making my suggestions really easy for your to implement in case you want them.

I would even go further and get rid of the pad_simple function all together since it is only called once.

### CODE REVIEW

**Comment by lagru** [comment]
Are these changes based on performance considerations or meant to make the code simpler / more readable?

> I would even go further and get rid of the pad_simple function all together since it is only called once.

True, but I think as its own function it enhances readability and documentation. `np.pad` is already quite long and verbose. So for now, I think I'll leave it as a function.

**Comment by hmaarrfk** [comment]
I would like to say performance, but it really depends on the use case. If you ar epadding a large array with a small amount of padding, it doesn't make much sense to traverse he memory twice.

For small arrays, using fill is probably faster than assining the boundaries smanually.

Your comment about readability is correct. I take that second suggestion back.

**Comment by lagru** [comment]
@hmaarrfk Would it be okay to close this for now? The parameter `fill_value` maybe useful for an optimization (see #3). In any case I'd prefer to discuss adding or removing this parameter inside #11358 where it would be more visible.

**Comment by hmaarrfk** [comment]
goodluck getting your pr in

**Pull request closed without merging**
